version: '3.7'
services:
  # my-app:
  # image: ${docker-registry}/my-app:1.0
  # ports:
  # - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always # fixes MongoNetworkError when mongodb is not ready when mongo-express starts
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
# volumes:
#   mongo-data:
#     driver: local
# volumes:
#    mongo-data:
#     #driver: local
#     driver_opts:
#       type: none
#       device: "/Users/aybouras/goinfre/delll"
#       o: bind
volumes:
    mongo-data:
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/Users/aybouras/Desktop/test'
            # device: '/Users/aybouras/goinfre' # prob of Ownership/Permissions 